version: '3'

vars:
  K8S_VERSION: rancher/k3s:v1.23.8-k3s2

tasks:
  install-prerequisites:
    desc: Install prerequisites (docker, kubectl, flux, k3d)
    cmds:
      - brew install docker kubernetes-cli fluxcd/tap/flux k3d
    silent: true
  
  k8s:create-cluster1:
    desc: Create a local k3s cluster (cluster-1)
    cmds:
      - >-
        k3d cluster create gitops-example-cluster-1
        --image "{{.K8S_VERSION}}"
        --servers 1
        --agents 2
        --api-port 6550
        --port "8080:80@loadbalancer"
        --k3s-arg '--disable=traefik@server:0'
        --k3s-arg '--flannel-backend=none@server:0'
        --k3s-node-label "agent=true@agent:0,1"
        --volume "$(pwd)/infrastructure/calico/calico.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
        --wait
    silent: true
  
  k8s:use-local-k3s-context:
    desc: Use the local k3s cluster (cluster-1) context
    cmds:
      - kubectl config use-context k3d-gitops-example-cluster-1
    silent: true
  
  k8s:delete-cluster1:
    desc: Delete local k3s cluster (cluster-1)
    cmds:
      - k3d cluster delete gitops-example-cluster-1
    silent: true
  
  k8s:verify-calico:
    deps: [k8s:use-local-k3s-context]
    desc: Verify that calico controller is deployed to local k3s cluster (cluster-1)
    cmds:
      - watch kubectl -n kube-system get deployments/calico-kube-controllers
    silent: true
  
  k8s:flux-check:
    deps: [k8s:use-local-k3s-context]
    desc: Run flux pre check against the local k3s cluster (cluster-1)
    cmds:
      - flux check --pre
    silent: true

  k8s:flux-bootstrap-cluster1:
    deps: [k8s:use-local-k3s-context]
    desc: Bootstrap flux to local k3s cluster (cluster-1)
    cmds:
      - >-
        flux bootstrap github
        --context=k3d-gitops-example-cluster-1
        --owner=${GITHUB_USER}
        --repository=${GITHUB_REPO}
        --branch=main
        --personal
        --network-policy=false
        --path=clusters/cluster-1
    silent: true