version: '3'

tasks:
  install-prerequisites:
    desc: Install prerequisites (docker, kubectl, flux, k3d)
    cmds:
      - brew install docker kubernetes-cli fluxcd/tap/flux k3d
    silent: true
  
  create-cluster1:
    desc: Install k3s cluster-1
    cmds:
      - >-
        k3d cluster create gitops-example-cluster-1
        --image rancher/k3s:v1.22.4-k3s1
        --servers 1
        --agents 1
        --api-port 6550
        --port "8080:80@loadbalancer"
        --k3s-arg '--disable=traefik@server:0'
        --k3s-arg '--flannel-backend=none@server:0'
        --volume "$(pwd)/infrastructure/calico/calico.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
        --wait

      - kubectl config use-context k3d-gitops-example-cluster-1
    silent: true
  
  create-cluster2:
    desc: Install k3s cluster-2
    cmds:
      - >-
        k3d cluster create gitops-example-cluster-2
        --image rancher/k3s:v1.22.4-k3s1
        --servers 1
        --agents 1
        --api-port 6550
        --port "8081:80@loadbalancer"
        --k3s-arg '--disable=traefik@server:0'
        --k3s-arg '--flannel-backend=none@server:0'
        --volume "$(pwd)/infrastructure/calico/calico.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
        --wait

      - kubectl config use-context k3d-gitops-example-cluster-2
    silent: true
  
  verify-calico:
    desc: Verify that calico controller is deployed
    cmds:
      - watch kubectl -n kube-system get deployments/calico-kube-controllers
    silent: true
  
  flux-check:
    desc: Run flux pre check
    cmds:
      - flux check --pre
    silent: true

  flux-bootstrap-cluster1:
    desc: Bootstrap flux for k3s cluster-1
    cmds:
      - >-
        flux bootstrap github
        --context=k3d-gitops-example-cluster-1
        --owner=${GITHUB_USER}
        --repository=${GITHUB_REPO}
        --branch=main
        --personal
        --network-policy=false
        --path=clusters/staging
    silent: true
  
  flux-bootstrap-cluster2:
    desc: Bootstrap flux for k3s cluster-2
    cmds:
      - >-
        flux bootstrap github
        --context=k3d-gitops-example-cluster-2
        --owner=${GITHUB_USER}
        --repository=${GITHUB_REPO}
        --branch=main
        --personal
        --network-policy=false
        --path=clusters/production
    silent: true