version: '3'

tasks:
  install-prerequisites:
    desc: Install prerequisites (docker, kubectl, flux, k3d)
    cmds:
      - brew install docker kubernetes-cli fluxcd/tap/flux k3d
    silent: true
  
  create-staging-cluster:
    desc: Install staging k3s cluster
    cmds:
      - >-
        k3d cluster create gitops-example-staging
        --image rancher/k3s:v1.19.14-k3s1
        --servers 1
        --agents 2
        --api-port 6550
        --port "8080:80@loadbalancer"
        --k3s-arg '--disable=traefik@server:0'
        --k3s-arg '--flannel-backend=none@server:0'
        --volume "$(pwd)/infrastructure/calico/calico.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
        --wait

      - kubectl config use-context k3d-gitops-example-staging
    silent: true
  
  create-production-cluster:
    desc: Install production k3s cluster
    cmds:
      - >-
        k3d cluster create gitops-example-production
        --image rancher/k3s:v1.19.14-k3s1
        --servers 1
        --agents 2
        --api-port 6550
        --port "8080:80@loadbalancer"
        --k3s-arg '--disable=traefik@server:0'
        --k3s-arg '--flannel-backend=none@server:0'
        --volume "$(pwd)/infrastructure/calico/calico.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
        --wait

      - kubectl config use-context k3d-gitops-example-production
    silent: true
  
  verify-calico:
    desc: Verify that calico controller is deployed
    cmds:
      - watch kubectl -n kube-system get deployments/calico-kube-controllers
    silent: true
  
  flux-check:
    desc: Run flux pre check
    cmds:
      - flux check --pre
    silent: true

  flux-bootstrap-staging:
    desc: Bootstrap flux for staging k3s cluster
    cmds:
      - >-
        flux bootstrap github
        --context=k3d-gitops-example-staging
        --owner=${GITHUB_USER}
        --repository=${GITHUB_REPO}
        --branch=main
        --personal
        --network-policy=false
        --path=clusters/staging
    silent: true
  
  flux-bootstrap-production:
    desc: Bootstrap flux for production k3s cluster
    cmds:
      - >-
        flux bootstrap github
        --context=k3d-gitops-example-production
        --owner=${GITHUB_USER}
        --repository=${GITHUB_REPO}
        --branch=main
        --personal
        --network-policy=false
        --path=clusters/production
    silent: true

  flux-hr:
    desc: List all Helm Releases
    cmds:
      - flux get hr -A
    silent: true
  
  flux-kz:
    desc: List all Kustomizations
    cmds:
      - flux get kustomizations -A
    silent: true