---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: api
  namespace: flux-system
spec:
  interval: 1m
  # url: https://github.com/terotuomala/k8s-express-api-example
  url: ssh://git@github.com/terotuomala/k8s-express-api-example
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
