---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: client
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/terotuomala/k8s-create-react-app-example
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
