---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      version: "v1.3.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    podSecurityStandard: disabled
    