---
architecture: standalone
auth:
  enabled: false
  usePassword: false
networkPolicy:
  enabled: true
  allowExternal: false
  ingressNSMatchLabels:
    name: api
  ingressNSPodMatchLabels:
    app: api
