---
architecture: standalone
auth:
  enabled: false
  sentinel: false
networkPolicy:
  enabled: true
  allowExternal: false
  extraIngress:
    - ports:
         - port: 6379
      from:
        - namespaceSelector:
            matchLabels:
              name: api
          podSelector:
            matchLabels:
              app: api