---
architecture: standalone
auth:
  enabled: false
  sentinel: false
networkPolicy:
  enabled: true
  allowExternal: true
  extraIngress:
    - ports:
        - port: 1234
      from:
        - namespaceSelector:
            - matchLabels:
                - name: api
        - podSelector:
            - matchLabels:
              - app: api