---
usePassword: false
cluster:
  enabled: false
master:
  persistence:
    enabled: false
networkPolicy:
  enabled: true
  ingressNSMatchLabels:
    name: api
  ingressNSPodMatchLabels:
    app: api
