---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
spec:
  releaseName: flagger/flagger
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      version: "1.7.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    prometheus.install: true
    meshProvider: nginx
