---
name: Lint

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint-yaml:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: "./clusters"
        config_file: "./.github/yamllint.config.yaml"
