name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Check for updates
        id: update
        run: |
          LONG_VERSION="$(flux -v)"
          VERSION="v${LONG_VERSION#*flux version }"

          flux install --version="${VERSION}" \
            --export > ./clusters/staging/flux-system/gotk-components.yaml

          echo "::set-output name=flux_version::$VERSION"

      - name: Create Pull Request for Flux update
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "Update Flux to version ${{ steps.update.outputs.flux_version }} [skip ci]"
            committer: "${{ github.repository_owner }} <${{ github.repository_owner }}@users.noreply.github.com>"
            author: "${{ github.repository_owner }} <${{ github.repository_owner }}@users.noreply.github.com>"
            assignees: "${{ github.repository_owner }}"
            branch: "flux/update-${{ steps.update.outputs.flux_version }}"
            delete-branch: true
            commit-message: "Update Flux to version ${{ steps.update.outputs.flux_version }} [skip ci]"
            body: |
              Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.update.outputs.flux_version }}
            labels: flux/update