name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Check for updates
        id: update
        run: |
          flux install --arch=amd64 \
            --export > ./clusters/staging/flux-system/gotk-components.yaml

          VERSION="$(flux -v)"
          echo "::set-output name=flux_version::$VERSION"

      - name: Create Pull Request for Flux update
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "Update Flux to version ${{ steps.update.outputs.flux_version }} [ci-skip]"
            committer: "terotuomala <terotuomala@users.noreply.github.com>"
            author: "terotuomala <terotuomala@users.noreply.github.com>"
            branch: "update-flux"
            delete-branch: true
            commit-message: "Update Flux to version ${{ steps.update.outputs.flux_version }} [ci-skip]"
            body: |
              Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.update.outputs.flux_version }}
            labels: flux/update